# Modified from https://github.com/freya022/discord-zstd-java/blob/d953a8f90624c2ce8438575fec14717fab216edb/.github/workflows/publish.yml

name: Publish
on:
  workflow_dispatch:

concurrency:
  group: 'publish'

jobs:
  build-opus:
    name: Build opus
    runs-on: ${{ matrix.os }}
    env:
      OPUS_REF: 'a8b13e40d751c7b40833b94fc9437c5c3439da89' #v1.6.0
      COMMON_CMAKE_FLAGS: "-DOPUS_BUILD_SHARED_LIBRARY=ON -DCMAKE_BUILD_TYPE=Release"

    outputs:
      version: ${{ steps.print-version.outputs.version }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    steps:
      - name: Opus build cache
        uses: actions/cache@v4
        id: opus-build-cache
        with:
          path: output
          key: ${{ runner.os }}-opus-build-cache-${{ env.OPUS_REF }}

      - name: Clone opus repo
        uses: actions/checkout@v6
        with:
          repository: xiph/opus
          ref: '${{ env.OPUS_REF }}'

      - name: Build opus
        if: ${{ steps.opus-build-cache.cache-hit != 'true' }}
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            for arch in x64 ARM64; do # We dont want Win32
              mkdir -p output/$arch
              mkdir build-$arch
              cd build-$arch
              cmake $COMMON_CMAKE_FLAGS -A $arch ..
              cmake --build . -j 4 --config Release
              cp Release/opus.dll ../output/$arch/libopus.dll
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            for arch in x64 ARM ARM64; do
              mkdir -p output/$arch
              mkdir build-$arch
              cd build-$arch
              if [[ "$arch" == "ARM64" ]]; then
                sudo apt update
                sudo apt install gcc-aarch64-linux-gnu
                cmake $COMMON_CMAKE_FLAGS -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc ..
              elif [[ "$arch" == "ARM" ]]; then
                sudo apt update
                sudo apt install gcc-arm-linux-gnueabihf
                cmake $COMMON_CMAKE_FLAGS -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc ..
              else
                cmake $COMMON_CMAKE_FLAGS ..
              fi
              cmake --build . -j 4
              cp libopus.so ../output/$arch/libopus.so
              cd ..
            done
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mkdir build output
            cd build
            cmake $COMMON_CMAKE_FLAGS "-DCMAKE_OSX_ARCHITECTURES=arm64;arm64e;x86_64;x86_64h" ..
            cmake --build . -j 4 --config Release
            cp libopus.dylib ../output/libopus.dylib
            cd ..
          fi

      - name: Publish Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: opus-${{ matrix.os }}
          path: output

  publish:
    needs: [build-opus]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout opus-java
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-disabled: true

      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          path: temp
          pattern: opus-*
          merge-multiple: true

      - name: Move Artifacts
        run: |
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/win32-x86-64
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/win32-aarch64
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/linux-x86-64
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/linux-arm
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/linux-aarch64
          mkdir -p src/main/resources/dev/freya02/opus/jda/natives/darwin
          cp temp/x64/libopus.dll src/main/resources/dev/freya02/opus/jda/natives/win32-x86-64/libopus.dll
          cp temp/ARM64/libopus.dll src/main/resources/dev/freya02/opus/jda/natives/win32-aarch64/libopus.dll
          cp temp/x64/libopus.so src/main/resources/dev/freya02/opus/jda/natives/linux-x86-64/libopus.so
          cp temp/ARM64/libopus.so src/main/resources/dev/freya02/opus/jda/natives/linux-aarch64/libopus.so
          cp temp/ARM/libopus.so src/main/resources/dev/freya02/opus/jda/natives/linux-arm/libopus.so
          cp temp/libopus.dylib src/main/resources/dev/freya02/opus/jda/natives/darwin/libopus.dylib

      - name: Build project
        run: ./gradlew build --no-configuration-cache

      - name: Publish project
        run: ./gradlew publish jreleaserDeploy --no-configuration-cache
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.MAVENCENTRAL_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
